# Generated by Django 3.0.3 on 2020-02-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='tkt_text',
        ),
    ]
