# Generated by Django 3.0.3 on 2020-02-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_system', '0002_auto_20200227_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='asset_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tkt_text',
            new_name='problem_desc',
        ),
    ]
