# Generated by Django 3.0.3 on 2020-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_system', '0004_auto_20200227_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asset_id',
            field=models.CharField(max_length=10),
        ),
    ]
